name: Build macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release
  
jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Install Ninja
        run: |
          brew install ninja
          
      - uses: actions/checkout@v4
      - name: Build project
        run: cmake -S . -B build -G "Ninja Multi-Config" && cmake --build build --config ${{ env.BUILD_TYPE }}
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-artifact
          path: build/${{ env.BUILD_TYPE }}
          if-no-files-found: ignore
          retention-days: 0
